apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patchesStrategicMerge:
  - backend-patch.yaml
  - frontend-patch.yaml
  - database-patch.yaml

images:
  - name: bank-backend
    newTag: latest
  - name: bank-frontend
    newName: REPLACE_WITH_ECR_FRONTEND
    newTag: latest
