apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: bank-app
type: Opaque
data:
  mongo-user: YmFua3VzZXI=     # base64('bankuser')
  mongo-password: YmFua3Bhc3M= # base64('bankpass')
