apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-database
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/milindpatle/Three-Tier-Project.git'  # Fixed capital T
    targetRevision: HEAD
    path: k8s/gitops/base/database
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bank-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true