{{- if .Values.backend }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image | quote }}
        env:
        - name: MONGO_URI
          value: "mongodb://{{ .Values.mongo.user }}:{{ .Values.mongo.password }}@mongo-0.mongo:27017/bankdb?authSource=admin"
        ports:
        - containerPort: 5000
{{- end}}
