apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bank-app

resources:
  # Backend
  - backend/deployment.yaml
  - backend/service.yaml

  # Frontend
  - frontend/deployment.yaml
  - frontend/service.yaml

  # Database
  - database/secret.yaml
  - database/service.yaml
  - database/statefulset.yaml
  # If you have PVC add this, else remove it:
  # - database/pvc.yaml
